/**
 * vibration_adc_uart.c
 * STM32L476RG — Vibration Sensor ADC Read + UART Transmit
 *
 * Reads analog vibration sensor on PA0 (ADC1_IN5) at 100 Hz,
 * formats the reading as a JSON line, and sends it over USART1
 * to the ESP32 which forwards it via WiFi to the Flask server.
 *
 * HOW TO USE IN CubeIDE
 * ─────────────────────
 * 1. Open your .ioc file → configure peripherals (see PINOUT below).
 * 2. Generate code.
 * 3. Copy the USER CODE sections below into your generated main.c.
 *
 * PINOUT (Nucleo-L476RG)
 * ──────────────────────
 *  PA0  → ADC1_IN5      (CN7 pin 28 / Arduino A0)  ← Vibration sensor OUT
 *  PA9  → USART1_TX     (CN10 pin 21)               → ESP32 RX (GPIO16)
 *  PA10 → USART1_RX     (CN10 pin 33)               ← ESP32 TX (GPIO17)
 *  GND  → GND           (common ground with ESP32)
 *
 * CubeIDE PERIPHERAL SETTINGS
 * ────────────────────────────
 *  ADC1:
 *    - Mode: Independent mode
 *    - Channel: IN5 (PA0)
 *    - Resolution: 12 bits
 *    - Continuous conversion: Disabled  (we trigger manually)
 *    - Data alignment: Right
 *    - Sampling time: 47.5 cycles
 *
 *  USART1:
 *    - Mode: Asynchronous
 *    - Baud rate: 115200
 *    - Word length: 8 bits
 *    - Parity: None
 *    - Stop bits: 1
 *
 *  NVIC: No interrupts needed — polling mode is used here.
 */

#include "main.h"
#include <stdio.h>
#include <string.h>

/* ── Handles generated by CubeIDE ─────────────────────────────── */
extern ADC_HandleTypeDef  hadc1;
extern UART_HandleTypeDef huart1;

/* ── Configuration ────────────────────────────────────────────── */
#define SENSOR_ID        "sensor_1"
#define VREF             3.3f        /* ADC reference voltage (V)   */
#define ADC_RESOLUTION   4095.0f    /* 12-bit                       */
#define SAMPLE_PERIOD_MS 10         /* 10 ms → 100 Hz               */
#define UART_TIMEOUT_MS  100

/* ── Internal helpers ─────────────────────────────────────────── */

/**
 * Read a single ADC conversion on ADC1 (blocking / polling).
 * Returns the raw 12-bit value (0–4095).
 */
static uint16_t adc_read(void)
{
    HAL_ADC_Start(&hadc1);
    HAL_ADC_PollForConversion(&hadc1, HAL_MAX_DELAY);
    uint16_t raw = (uint16_t)HAL_ADC_GetValue(&hadc1);
    HAL_ADC_Stop(&hadc1);
    return raw;
}

/**
 * Transmit a null-terminated string over USART1.
 */
static void uart_send(const char *str)
{
    HAL_UART_Transmit(&huart1,
                      (uint8_t *)str,
                      (uint16_t)strlen(str),
                      UART_TIMEOUT_MS);
}

/* ── Main application entry point ─────────────────────────────── */

/**
 * Call this function from main() inside the USER CODE BEGIN 2 region,
 * then loop it inside the while(1) USER CODE loop.
 *
 * Example in generated main.c:
 *
 *   // USER CODE BEGIN 2
 *   vibration_run();   // <-- never returns, loops internally
 *   // USER CODE END 2
 */
void vibration_run(void)
{
    char    json_buf[80];
    uint16_t raw;
    float    voltage;

    for (;;)
    {
        /* 1. Sample ADC */
        raw     = adc_read();
        voltage = ((float)raw / ADC_RESOLUTION) * VREF;

        /* 2. Build JSON line
         *    Format: {"sensor_id":"sensor_1","raw":2048,"voltage":1.654}\n
         *    ESP32 reads until '\n' so the newline acts as a delimiter.
         */
        snprintf(json_buf, sizeof(json_buf),
                 "{\"sensor_id\":\"%s\",\"raw\":%u,\"voltage\":%.3f}\n",
                 SENSOR_ID, raw, voltage);

        /* 3. Send over UART to ESP32 */
        uart_send(json_buf);

        /* 4. Wait for next sample (100 Hz) */
        HAL_Delay(SAMPLE_PERIOD_MS);
    }
}
